#!/bin/bash

CURRENT_DIR=$(pwd);

cd /d/NSCC/Winter\ 2026/PROG2400;
echo "===========PROG2400===========";
git status;
cd /d/NSCC/Winter\ 2026/PROG2500;
echo "===========PROG2500===========";
git status;
cd /d/NSCC/Winter\ 2026/INFT3075;
echo "===========INFT3075===========";
git status;
cd /d/NSCC/Winter\ 2026/INFT4000;
echo "===========INFT4000===========";
git status;
cd /d/NSCC/Winter\ 2026/ICOM2073;
echo "===========ICOM273===========";
git status;
cd /d/NSCC/Winter\ 2026/PROG3300;
echo "===========PROG3300===========";
git status;

cd "$CURRENT_DIR";
