#!/bin/bash

CURRENT_DIR=$(pwd);

cd /d/NSCC/Fall\ 2025/PROG2100;
echo "===========PROG2100===========";
git status;
cd /d/NSCC/Fall\ 2025/PROG2200;
echo "===========PROG2200===========";
git status;
cd /d/NSCC/Fall\ 2025/MOBI3002;
echo "===========MOBI3002===========";
git status;
cd /d/NSCC/Fall\ 2025/INET2005;
echo "===========INET2005===========";
git status;
cd /d/NSCC/Fall\ 2025/INFT2100;
echo "===========INFT2100===========";
git status;
cd /d/NSCC/Fall\ 2025/ICOM2702;
echo "===========ICOM2702===========";
git status;

cd "$CURRENT_DIR";
